# Generated by Django 2.1.4 on 2019-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_student_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_url', models.CharField(max_length=500)),
                ('project_last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Student Projects',
            },
        ),
    ]
