# Generated by Django 2.1.1 on 2019-05-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='project_name',
            field=models.CharField(choices=[('Portfolio', 'Dev Portfolio'), ('Passion', 'Passion Project'), ('Other', 'Other')], max_length=200),
        ),
    ]
