# Generated by Django 2.1.4 on 2019-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcm_app', '0002_auto_20190530_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentproject',
            name='project_name',
            field=models.CharField(choices=[('Portfolio', 'Dev Portfolio'), ('Passion', 'Passion Project'), ('Other', 'Other Project')], max_length=200),
        ),
    ]
